language: node_js
before_script:
  - git config --global user.email "john@doe.com"
  - git config --global user.name "John Doe"
script:
  - npm test
  - npm run send-coverage
node_js:
  - "6"
  - "7"
os:
  - linux
sudo: false
