language: node_js
before_script:
  - git config --global user.email "john@doe.com"
  - git config --global user.name "John Doe"
script:
  - npm install node-coverage-server -g
  - npm test
  - npm run coverage
  - cat coverage/lcov.info | node-coverage-cli --url https://node-coverage-server.herokuapp.com
node_js:
  - "4"
  - "6"
  - "7"
os:
  - linux
  - osx
sudo: false
