language: node_js
before_script:
  - git config --global user.email "john@doe.com"
  - git config --global user.name "John Doe"
script:
  - npm install lcov-server -g
  - npm test
  - npm run coverage
  - cat coverage/lcov.info | lcov-server --upload https://lcov-server.herokuapp.com
node_js:
  - "6"
  - "8"
os:
  - linux
  - osx
sudo: false
